"""
Add projects and general chat sessions

Creates five tables:
  projects              — named workspaces
  project_sources       — papers added to a project (arxiv or user upload)
  project_chat_messages — single persisted chat thread per project
  chat_sessions         — general chat threads (ChatGPT-style sidebar)
  chat_messages         — messages within a general chat session

Design notes:
  - project_sources.paper_id → papers.id (UUID) so it works identically
    for both arxiv and user_upload papers.
  - UNIQUE(project_id, paper_id) prevents duplicate sources.
  - All FK relationships use CASCADE so deleting a project or session
    cleans up its children automatically.
  - projects.overview is NULL until first generated by the LLM.
  - chat_sessions.title is NULL on creation and auto-set from the first
    user message by the repository layer.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004_add_projects"
down_revision = "3d4f5a6b7c8e"   # add_user_upload_and_flashcards
branch_labels = None
depends_on = None


def upgrade():

    # =========================================================================
    # Table: projects
    # =========================================================================

    op.create_table(
        "projects",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),

        # AI-generated summary of all sources — NULL until first generated
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("overview_generated_at", sa.DateTime(timezone=True), nullable=True),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
    )

    op.create_index("ix_projects_created_at", "projects", ["created_at"])
    op.create_index("ix_projects_updated_at", "projects", ["updated_at"])

    # =========================================================================
    # Table: project_sources
    # =========================================================================

    op.create_table(
        "project_sources",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "paper_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("papers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
    )

    op.create_unique_constraint(
        "uq_project_sources_project_paper",
        "project_sources",
        ["project_id", "paper_id"],
    )
    op.create_index("ix_project_sources_project_id", "project_sources", ["project_id"])
    op.create_index("ix_project_sources_paper_id", "project_sources", ["paper_id"])

    # =========================================================================
    # Table: project_chat_messages
    # =========================================================================

    op.create_table(
        "project_chat_messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "project_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("projects.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # "user" | "assistant"
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
    )

    # Composite index: fetching all messages for a project in chronological order
    op.create_index(
        "ix_project_chat_messages_project_created",
        "project_chat_messages",
        ["project_id", "created_at"],
    )

    # =========================================================================
    # Table: chat_sessions
    # =========================================================================

    op.create_table(
        "chat_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        # NULL on creation — auto-set from first user message
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
    )

    op.create_index("ix_chat_sessions_updated_at", "chat_sessions", ["updated_at"])
    op.create_index("ix_chat_sessions_created_at", "chat_sessions", ["created_at"])

    # =========================================================================
    # Table: chat_messages
    # =========================================================================

    op.create_table(
        "chat_messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("chat_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # "user" | "assistant"
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("timezone('utc', now())"),
        ),
    )

    # Composite index: fetch all messages for a session in chronological order
    op.create_index(
        "ix_chat_messages_session_created",
        "chat_messages",
        ["session_id", "created_at"],
    )


def downgrade():

    # chat_messages
    op.drop_index("ix_chat_messages_session_created", table_name="chat_messages")
    op.drop_table("chat_messages")

    # chat_sessions
    op.drop_index("ix_chat_sessions_updated_at", table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_created_at", table_name="chat_sessions")
    op.drop_table("chat_sessions")

    # project_chat_messages
    op.drop_index("ix_project_chat_messages_project_created", table_name="project_chat_messages")
    op.drop_table("project_chat_messages")

    # project_sources
    op.drop_index("ix_project_sources_paper_id", table_name="project_sources")
    op.drop_index("ix_project_sources_project_id", table_name="project_sources")
    op.drop_constraint("uq_project_sources_project_paper", "project_sources", type_="unique")
    op.drop_table("project_sources")

    # projects
    op.drop_index("ix_projects_updated_at", table_name="projects")
    op.drop_index("ix_projects_created_at", table_name="projects")
    op.drop_table("projects")
